sudo: true

language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk7
      env: TARGET=java
    - os: linux
      jdk: oraclejdk8
      env: TARGET=java
    - os: linux
      jdk: oraclejdk7
      env: TARGET=go

before_install:
  - ./.travis/before-install-$TRAVIS_OS_NAME-$TARGET.sh

script:
  - cd runtime-testsuite; ../.travis/run-tests-$TARGET.sh

